# SPDX-FileCopyrightText: 2023 Iconica
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: flutter_appshell_userstories_workspace

environment:
  sdk: '>=3.1.0 <4.0.0'
dev_dependencies:
  melos: ^3.0.1
